services:
  app:
    build: .
    container_name: go-http-server
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT:-3000}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: go-http-server-network
